// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WpfApp1.Models;

public partial class Saram
{
    public int Id { get; set; }

    public int? Age { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string Telephone { get; set; }

    public bool? Gender { get; set; }
}

public partial class Saram2
{
	public int Id { get; set; }

	public int? Age { get; set; }

	public string Name { get; set; }

	public string Address { get; set; }

	public string Telephone { get; set; }

	public bool? Gender { get; set; }
}